background:	#753B00
foreground:	#99F800

color0:		#2C1600
color1:		#E14125

color2:		#00FF00
color3:		#FFFF00

color4:		#00AAFF
color5:		#57FC4B

color6:		#35FFBC
color7:		#A8A8A8

color8:		#4D4D4D
color9:		#FF584C

color10:		#53FF5E
color11:		#FCFF5C

color12:		#2CE3FF
color13:		#92FF3E

color14:		#6BFEAD
color15:		#CCCCCC
